# Generated by Django 2.1 on 2019-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptvc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
