# Generated by Django 2.1 on 2019-03-20 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptvc_app', '0003_auto_20190320_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
