# Generated by Django 2.1 on 2019-03-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptvc_app', '0007_remove_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
