# Generated by Django 2.1 on 2019-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptvc_app', '0009_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
